'use client';
import "./globals.css";
import { Header } from "@/components/Header";
import React, { useState } from "react";
import Sidebar from "@/components/Sidebar";
import { Footer } from "@/components/Footer";
import { Provider } from "react-redux";
import store from "@/store/store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const toggleSidebar = () => {
    setSidebarOpen((prev) => !prev);
  };

  return (
    <html lang="en">
      <body >
        <Provider store={store}>
          <Header onSidebarToggle={toggleSidebar} sidebarOpen={sidebarOpen} />
          <Sidebar open={sidebarOpen} onClose={() => setSidebarOpen(false)} />
        <main>{children}</main>
        <Footer/>
        </Provider>
      </body>
    </html>
  );
}
